# Data Cleaning & Wrangling:
In this project, we will enhance the quality of a dataset containing 100 generic medication names by cleaning and restructuring the data. Our goal is to process a raw text file of medication names and organize them into two distinct columns: one for the medication name and another for the medication class. This process will involve data extraction, transformation, and validation to ensure accuracy and consistency. The cleaned dataset will be formatted for future use, ensuring it is well-structured and accessible for other teams to leverage in their ongoing work.


In [44]:
# Initial Import
import pandas as pd

In [45]:
pd.read_csv('/content/1000 Generic Medication Names_NHC.txt',sep='\t')

1. Acetaminophen Tablet (500 mg) - Analgesic
0    2. Ibuprofen Tablet (200 mg) - Nonsteroidal An...
1    3. Aspirin Tablet (81 mg) - Platelet Aggregati...
2    4. Naproxen Tablet (250 mg) - Nonsteroidal Ant...
3        5. Morphine Tablet (15 mg) - Opioid Analgesic
4        6. Oxycodone Tablet (5 mg) - Opioid Analgesic
..                                                 ...
994  996. Alprostadil Urethral Suppository (250 mcg...
995  997. Phentolamine Injection (1 mg/mL) - Alpha-...
996  998. Papaverine Injection (30 mg/mL) - Vasodil...
997   999. Yohimbine Tablet (5.4 mg) - Alpha-2 Blocker
998  1000. L-Arginine Tablet (500 mg) - Amino Acid ...

[999 rows x 1 columns]

In [46]:
# The first row is an header instead of the row, we need to correct this
df_med = pd.read_csv('/content/1000 Generic Medication Names_NHC.txt',sep='\t', header=None)
df_med

0
0         1. Acetaminophen Tablet (500 mg) - Analgesic
1    2. Ibuprofen Tablet (200 mg) - Nonsteroidal An...
2    3. Aspirin Tablet (81 mg) - Platelet Aggregati...
3    4. Naproxen Tablet (250 mg) - Nonsteroidal Ant...
4        5. Morphine Tablet (15 mg) - Opioid Analgesic
..                                                 ...
995  996. Alprostadil Urethral Suppository (250 mcg...
996  997. Phentolamine Injection (1 mg/mL) - Alpha-...
997  998. Papaverine Injection (30 mg/mL) - Vasodil...
998   999. Yohimbine Tablet (5.4 mg) - Alpha-2 Blocker
999  1000. L-Arginine Tablet (500 mg) - Amino Acid ...

[1000 rows x 1 columns]

In [47]:
# Let examine our dataframe
df_med[0][0]

'1. Acetaminophen Tablet (500 mg) - Analgesic'

In [48]:
# The dataframe is just a single column, let's check the type and then split the str in a list
type(df_med[0][0])

str

In [49]:
# Splitting the Str into a list
df_med[0][0].split('.')

['1', ' Acetaminophen Tablet (500 mg) - Analgesic']

In [50]:
# It's seem that the medication class is distinguished with a "-"
df_med[0][0].split('-')

['1. Acetaminophen Tablet (500 mg) ', ' Analgesic']

In [51]:
# Confirming if the split was succesful
type(df_med[0][0].split('-'))

list

To better organize the data, we can introduce an additional column specifically for the medication class and it seems that using the split method would be the best method to extract our information





In [52]:
df_med['Med_class'] = df_med[0].apply(lambda x : x.split("-")[1])
df_med

0  \
0         1. Acetaminophen Tablet (500 mg) - Analgesic   
1    2. Ibuprofen Tablet (200 mg) - Nonsteroidal An...   
2    3. Aspirin Tablet (81 mg) - Platelet Aggregati...   
3    4. Naproxen Tablet (250 mg) - Nonsteroidal Ant...   
4        5. Morphine Tablet (15 mg) - Opioid Analgesic   
..                                                 ...   
995  996. Alprostadil Urethral Suppository (250 mcg...   
996  997. Phentolamine Injection (1 mg/mL) - Alpha-...   
997  998. Papaverine Injection (30 mg/mL) - Vasodil...   
998   999. Yohimbine Tablet (5.4 mg) - Alpha-2 Blocker   
999  1000. L-Arginine Tablet (500 mg) - Amino Acid ...   

                           Med_class  
0                          Analgesic  
1                  Nonsteroidal Anti  
2     Platelet Aggregation Inhibitor  
3                  Nonsteroidal Anti  
4                   Opioid Analgesic  
..                               ...  
995          Prostaglandin E1 Analog  
996                            Alpha  
997                      Vasodilator  
998                            Alpha  
999        Arginine Tablet (500 mg)   

[1000 rows x 2 columns]

However, something is wrong with row 998. It's only has the word "Alpha". Let's observe what went wrong

In [53]:
# It's seem that the "-" within the text was also split, it is likely occurring in other rows as well
df_med[0][998]

'999. Yohimbine Tablet (5.4 mg) - Alpha-2 Blocker'

In [54]:
# Additionally other "-" are present throughout the text as well
df_med[0][999]

'1000. L-Arginine Tablet (500 mg) - Amino Acid Supplement'

It seems that the .split method was not efficient enough to properly distinguish our medication classes, as other instances of "-" were also being split unintentionally

In [55]:
# Let's try if we can continue to keep on using split method by experimenting
df_med[0][999].split('.')

['1000', ' L-Arginine Tablet (500 mg) - Amino Acid Supplement']

In [56]:
# Splitting the string from the 999th row, 0th column at '-' and taking the first part
df_med[0][999].split('-')[0]

'1000. L'

In [57]:
# Split the digitals from the medication name
df_med[0][998].split('.')

['999', ' Yohimbine Tablet (5', '4 mg) - Alpha-2 Blocker']

In [58]:
# Ensure that only the first occurrence of hte period is used to split the string
df_med[0][998].split('.',maxsplit=1)

['999', ' Yohimbine Tablet (5.4 mg) - Alpha-2 Blocker']

One approach could be to split the column into two parts: one for the med_name and another for the med_class. By isolating just the med_name and then splitting based on the first occurrence of the hyphen "-", we can avoid issues where additional hyphens within the med_class could interfere with the intended structure

In [59]:
# Split the column by the first hyphen and create 'med_name' and 'med_class_2'
df_med[['med_name', 'med_class_2']] = df_med[0].astype(str).str.split('-', expand=True, n=1)

# Now, modify 'med_name' to split everything after the period (.)
df_med['med_name'] = df_med['med_name'].apply(lambda x: x.split('.', 1)[1].strip() if '.' in x else x)

df_med

0  \
0         1. Acetaminophen Tablet (500 mg) - Analgesic   
1    2. Ibuprofen Tablet (200 mg) - Nonsteroidal An...   
2    3. Aspirin Tablet (81 mg) - Platelet Aggregati...   
3    4. Naproxen Tablet (250 mg) - Nonsteroidal Ant...   
4        5. Morphine Tablet (15 mg) - Opioid Analgesic   
..                                                 ...   
995  996. Alprostadil Urethral Suppository (250 mcg...   
996  997. Phentolamine Injection (1 mg/mL) - Alpha-...   
997  998. Papaverine Injection (30 mg/mL) - Vasodil...   
998   999. Yohimbine Tablet (5.4 mg) - Alpha-2 Blocker   
999  1000. L-Arginine Tablet (500 mg) - Amino Acid ...   

                           Med_class  \
0                          Analgesic   
1                  Nonsteroidal Anti   
2     Platelet Aggregation Inhibitor   
3                  Nonsteroidal Anti   
4                   Opioid Analgesic   
..                               ...   
995          Prostaglandin E1 Analog   
996                            Alpha   
997                      Vasodilator   
998                            Alpha   
999        Arginine Tablet (500 mg)    

                                       med_name  \
0                 Acetaminophen Tablet (500 mg)   
1                     Ibuprofen Tablet (200 mg)   
2                        Aspirin Tablet (81 mg)   
3                      Naproxen Tablet (250 mg)   
4                       Morphine Tablet (15 mg)   
..                                          ...   
995  Alprostadil Urethral Suppository (250 mcg)   
996            Phentolamine Injection (1 mg/mL)   
997             Papaverine Injection (30 mg/mL)   
998                   Yohimbine Tablet (5.4 mg)   
999                                           L   

                                          med_class_2  
0                                           Analgesic  
1                 Nonsteroidal Anti-Inflammatory Drug  
2                      Platelet Aggregation Inhibitor  
3                 Nonsteroidal Anti-Inflammatory Drug  
4                                    Opioid Analgesic  
..                                                ...  
995                           Prostaglandin E1 Analog  
996                                     Alpha-Blocker  
997                                       Vasodilator  
998                                   Alpha-2 Blocker  
999  Arginine Tablet (500 mg) - Amino Acid Supplement  

[1000 rows x 4 columns]

Okay Row 998 is fixed however, Row 999 is still producing errors, as the first "-" is within the medication name. As a result, the med_name only contains the L while the rest of the name is incorporated into the med_class_2. Let's examine the issue.

In [60]:
# Examining med_name column
df_med[df_med['med_name'] == 'L']

0  \
267  268. L-Arginine Tablet (500 mg) - Amino Acid S...   
437  438. L-Arginine Tablet (500 mg) - Amino Acid S...   
607  608. L-Arginine Tablet (500 mg) - Amino Acid S...   
633  634. L-Arginine Tablet (1,000 mg) - Amino Acid...   
803  804. L-Arginine Tablet (500 mg) - Amino Acid S...   
829  830. L-Arginine Tablet (1,000 mg) - Amino Acid...   
999  1000. L-Arginine Tablet (500 mg) - Amino Acid ...   

                       Med_class med_name  \
267    Arginine Tablet (500 mg)         L   
437    Arginine Tablet (500 mg)         L   
607    Arginine Tablet (500 mg)         L   
633  Arginine Tablet (1,000 mg)         L   
803    Arginine Tablet (500 mg)         L   
829  Arginine Tablet (1,000 mg)         L   
999    Arginine Tablet (500 mg)         L   

                                           med_class_2  
267   Arginine Tablet (500 mg) - Amino Acid Supplement  
437   Arginine Tablet (500 mg) - Amino Acid Supplement  
607   Arginine Tablet (500 mg) - Amino Acid Supplement  
633  Arginine Tablet (1,000 mg) - Amino Acid Supple...  
803   Arginine Tablet (500 mg) - Amino Acid Supplement  
829  Arginine Tablet (1,000 mg) - Amino Acid Supple...  
999   Arginine Tablet (500 mg) - Amino Acid Supplement

In [61]:
# let's rename the 'L' to the proper name
df_med.loc[df_med['med_name'] == 'L', 'med_name'] = 'L-Arginine Tablet (500 mg)'
df_med

0  \
0         1. Acetaminophen Tablet (500 mg) - Analgesic   
1    2. Ibuprofen Tablet (200 mg) - Nonsteroidal An...   
2    3. Aspirin Tablet (81 mg) - Platelet Aggregati...   
3    4. Naproxen Tablet (250 mg) - Nonsteroidal Ant...   
4        5. Morphine Tablet (15 mg) - Opioid Analgesic   
..                                                 ...   
995  996. Alprostadil Urethral Suppository (250 mcg...   
996  997. Phentolamine Injection (1 mg/mL) - Alpha-...   
997  998. Papaverine Injection (30 mg/mL) - Vasodil...   
998   999. Yohimbine Tablet (5.4 mg) - Alpha-2 Blocker   
999  1000. L-Arginine Tablet (500 mg) - Amino Acid ...   

                           Med_class  \
0                          Analgesic   
1                  Nonsteroidal Anti   
2     Platelet Aggregation Inhibitor   
3                  Nonsteroidal Anti   
4                   Opioid Analgesic   
..                               ...   
995          Prostaglandin E1 Analog   
996                            Alpha   
997                      Vasodilator   
998                            Alpha   
999        Arginine Tablet (500 mg)    

                                       med_name  \
0                 Acetaminophen Tablet (500 mg)   
1                     Ibuprofen Tablet (200 mg)   
2                        Aspirin Tablet (81 mg)   
3                      Naproxen Tablet (250 mg)   
4                       Morphine Tablet (15 mg)   
..                                          ...   
995  Alprostadil Urethral Suppository (250 mcg)   
996            Phentolamine Injection (1 mg/mL)   
997             Papaverine Injection (30 mg/mL)   
998                   Yohimbine Tablet (5.4 mg)   
999                  L-Arginine Tablet (500 mg)   

                                          med_class_2  
0                                           Analgesic  
1                 Nonsteroidal Anti-Inflammatory Drug  
2                      Platelet Aggregation Inhibitor  
3                 Nonsteroidal Anti-Inflammatory Drug  
4                                    Opioid Analgesic  
..                                                ...  
995                           Prostaglandin E1 Analog  
996                                     Alpha-Blocker  
997                                       Vasodilator  
998                                   Alpha-2 Blocker  
999  Arginine Tablet (500 mg) - Amino Acid Supplement  

[1000 rows x 4 columns]

Now Let's do the same with med_class_2

In [62]:
# Examining med_name column
df_med[df_med['med_class_2'] == 'Arginine Tablet (500 mg) - Amino Acid Supplement']

0  \
267  268. L-Arginine Tablet (500 mg) - Amino Acid S...   
437  438. L-Arginine Tablet (500 mg) - Amino Acid S...   
607  608. L-Arginine Tablet (500 mg) - Amino Acid S...   
803  804. L-Arginine Tablet (500 mg) - Amino Acid S...   
999  1000. L-Arginine Tablet (500 mg) - Amino Acid ...   

                     Med_class                    med_name  \
267  Arginine Tablet (500 mg)   L-Arginine Tablet (500 mg)   
437  Arginine Tablet (500 mg)   L-Arginine Tablet (500 mg)   
607  Arginine Tablet (500 mg)   L-Arginine Tablet (500 mg)   
803  Arginine Tablet (500 mg)   L-Arginine Tablet (500 mg)   
999  Arginine Tablet (500 mg)   L-Arginine Tablet (500 mg)   

                                          med_class_2  
267  Arginine Tablet (500 mg) - Amino Acid Supplement  
437  Arginine Tablet (500 mg) - Amino Acid Supplement  
607  Arginine Tablet (500 mg) - Amino Acid Supplement  
803  Arginine Tablet (500 mg) - Amino Acid Supplement  
999  Arginine Tablet (500 mg) - Amino Acid Supplement

In [63]:
df_med.loc[df_med['med_class_2'] == 'Arginine Tablet (500 mg) - Amino Acid Supplement', 'med_class_2'] = 'Amino Acid Supplement'
df_med

0  \
0         1. Acetaminophen Tablet (500 mg) - Analgesic   
1    2. Ibuprofen Tablet (200 mg) - Nonsteroidal An...   
2    3. Aspirin Tablet (81 mg) - Platelet Aggregati...   
3    4. Naproxen Tablet (250 mg) - Nonsteroidal Ant...   
4        5. Morphine Tablet (15 mg) - Opioid Analgesic   
..                                                 ...   
995  996. Alprostadil Urethral Suppository (250 mcg...   
996  997. Phentolamine Injection (1 mg/mL) - Alpha-...   
997  998. Papaverine Injection (30 mg/mL) - Vasodil...   
998   999. Yohimbine Tablet (5.4 mg) - Alpha-2 Blocker   
999  1000. L-Arginine Tablet (500 mg) - Amino Acid ...   

                           Med_class  \
0                          Analgesic   
1                  Nonsteroidal Anti   
2     Platelet Aggregation Inhibitor   
3                  Nonsteroidal Anti   
4                   Opioid Analgesic   
..                               ...   
995          Prostaglandin E1 Analog   
996                            Alpha   
997                      Vasodilator   
998                            Alpha   
999        Arginine Tablet (500 mg)    

                                       med_name  \
0                 Acetaminophen Tablet (500 mg)   
1                     Ibuprofen Tablet (200 mg)   
2                        Aspirin Tablet (81 mg)   
3                      Naproxen Tablet (250 mg)   
4                       Morphine Tablet (15 mg)   
..                                          ...   
995  Alprostadil Urethral Suppository (250 mcg)   
996            Phentolamine Injection (1 mg/mL)   
997             Papaverine Injection (30 mg/mL)   
998                   Yohimbine Tablet (5.4 mg)   
999                  L-Arginine Tablet (500 mg)   

                              med_class_2  
0                               Analgesic  
1     Nonsteroidal Anti-Inflammatory Drug  
2          Platelet Aggregation Inhibitor  
3     Nonsteroidal Anti-Inflammatory Drug  
4                        Opioid Analgesic  
..                                    ...  
995               Prostaglandin E1 Analog  
996                         Alpha-Blocker  
997                           Vasodilator  
998                       Alpha-2 Blocker  
999                 Amino Acid Supplement  

[1000 rows x 4 columns]

Everything looks Good. Let's drop the Med_class column and rename the med_class_2 column to ensure proper data cleaning

In [64]:
# Dropping med_class
df_med.drop(columns=['Med_class'], inplace=True)
df_med

0  \
0         1. Acetaminophen Tablet (500 mg) - Analgesic   
1    2. Ibuprofen Tablet (200 mg) - Nonsteroidal An...   
2    3. Aspirin Tablet (81 mg) - Platelet Aggregati...   
3    4. Naproxen Tablet (250 mg) - Nonsteroidal Ant...   
4        5. Morphine Tablet (15 mg) - Opioid Analgesic   
..                                                 ...   
995  996. Alprostadil Urethral Suppository (250 mcg...   
996  997. Phentolamine Injection (1 mg/mL) - Alpha-...   
997  998. Papaverine Injection (30 mg/mL) - Vasodil...   
998   999. Yohimbine Tablet (5.4 mg) - Alpha-2 Blocker   
999  1000. L-Arginine Tablet (500 mg) - Amino Acid ...   

                                       med_name  \
0                 Acetaminophen Tablet (500 mg)   
1                     Ibuprofen Tablet (200 mg)   
2                        Aspirin Tablet (81 mg)   
3                      Naproxen Tablet (250 mg)   
4                       Morphine Tablet (15 mg)   
..                                          ...   
995  Alprostadil Urethral Suppository (250 mcg)   
996            Phentolamine Injection (1 mg/mL)   
997             Papaverine Injection (30 mg/mL)   
998                   Yohimbine Tablet (5.4 mg)   
999                  L-Arginine Tablet (500 mg)   

                              med_class_2  
0                               Analgesic  
1     Nonsteroidal Anti-Inflammatory Drug  
2          Platelet Aggregation Inhibitor  
3     Nonsteroidal Anti-Inflammatory Drug  
4                        Opioid Analgesic  
..                                    ...  
995               Prostaglandin E1 Analog  
996                         Alpha-Blocker  
997                           Vasodilator  
998                       Alpha-2 Blocker  
999                 Amino Acid Supplement  

[1000 rows x 3 columns]

In [65]:
# Let's also rename the med_class_2 to just med_class
df_med.rename(columns={'med_class_2': 'med_class'}, inplace=True)

In [70]:
# Let's also rename the orignial column into "original_descr"
df_med.rename(columns={0: 'original_descr'}, inplace=True)

In [71]:
# Checking
df_med

original_descr  \
0         1. Acetaminophen Tablet (500 mg) - Analgesic   
1    2. Ibuprofen Tablet (200 mg) - Nonsteroidal An...   
2    3. Aspirin Tablet (81 mg) - Platelet Aggregati...   
3    4. Naproxen Tablet (250 mg) - Nonsteroidal Ant...   
4        5. Morphine Tablet (15 mg) - Opioid Analgesic   
..                                                 ...   
995  996. Alprostadil Urethral Suppository (250 mcg...   
996  997. Phentolamine Injection (1 mg/mL) - Alpha-...   
997  998. Papaverine Injection (30 mg/mL) - Vasodil...   
998   999. Yohimbine Tablet (5.4 mg) - Alpha-2 Blocker   
999  1000. L-Arginine Tablet (500 mg) - Amino Acid ...   

                                       med_name  \
0                 Acetaminophen Tablet (500 mg)   
1                     Ibuprofen Tablet (200 mg)   
2                        Aspirin Tablet (81 mg)   
3                      Naproxen Tablet (250 mg)   
4                       Morphine Tablet (15 mg)   
..                                          ...   
995  Alprostadil Urethral Suppository (250 mcg)   
996            Phentolamine Injection (1 mg/mL)   
997             Papaverine Injection (30 mg/mL)   
998                   Yohimbine Tablet (5.4 mg)   
999                  L-Arginine Tablet (500 mg)   

                                med_class  
0                               Analgesic  
1     Nonsteroidal Anti-Inflammatory Drug  
2          Platelet Aggregation Inhibitor  
3     Nonsteroidal Anti-Inflammatory Drug  
4                        Opioid Analgesic  
..                                    ...  
995               Prostaglandin E1 Analog  
996                         Alpha-Blocker  
997                           Vasodilator  
998                       Alpha-2 Blocker  
999                 Amino Acid Supplement  

[1000 rows x 3 columns]

Everything looks goods. After performing the data cleaning and wrangling our dataframe is ready for use. Let's convert it into a new csv file to future use.

In [72]:
df_med.to_csv('Cleaned_Generic_Medication_NHC.csv', index=False)